import { ArrowLeftOutlined } from '@ant-design/icons'
import { Button, Layout, Spin, Tooltip } from 'antd'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useQuery } from 'react-query'
import { Details } from '../components/Details'
import { ResponsiveRow } from '../components/ResponsiveRow'
import { getDetails } from '../lib/getMediaDetails'
import { OMDBAPISuccessDetails } from '../models/omdb'
import config from '../utils/config'

const { Header, Content } = Layout

export default function MediaDetails(): JSX.Element {
  const router = useRouter()
  const { id } = router.query
  const getDetailsQuery = getDetails(String(id))

  const { data, isLoading, isError } = useQuery<OMDBAPISuccessDetails, Error>(
    ['details', id],
    getDetailsQuery
  )

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Head>
        <title>
          {config.appName} | {id}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!id && (
        <div className="center">
          <p>ID not provided!</p>
        </div>
      )}
      {isLoading ? (
        <div className="center">
          <Spin size="large" />
        </div>
      ) : (
        <>
          <Header>
            <ResponsiveRow leftColumn={<Return />}>
              {!isLoading && !isError && (
                <div className="center-text">
                  <span className="app-title">
                    {data?.Title} ({data?.Year})
                  </span>
                </div>
              )}
            </ResponsiveRow>
          </Header>
          <Content style={{ padding: '20px 40px' }}>
            {data && <Details data={data} />}
          </Content>
        </>
      )}
    </Layout>
  )
}

const Return = () => (
  <Tooltip title="Go back">
    <Link href="/" passHref>
      <Button
        type="primary"
        shape="circle"
        icon={<ArrowLeftOutlined />}
      ></Button>
    </Link>
  </Tooltip>
)
