import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useQuery } from 'react-query'
import { getDetails } from '../lib/getMediaDetails'
import { OMDBAPISuccess } from '../models/omdb'
import styles from '../styles/Home.module.css'
import config from '../utils/config'

export default function MediaDetails(): JSX.Element {
  const router = useRouter()
  const { id } = router.query

  return (
    <div className={styles.container}>
      <Head>
        <title>{config.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {id ? (
          <MovieDetails id={id} />
        ) : (
          <div>
            <p>ID not provided!</p>
            <Link href="/">
              <a>Go back</a>
            </Link>
          </div>
        )}
      </div>
    </div>
  )
}

const MovieDetails = ({ id }) => {
  const getDetailsQuery = getDetails(id)
  const { data, isLoading, isError, error } = useQuery<OMDBAPISuccess, Error>(
    ['details', id],
    getDetailsQuery
  )

  return (
    <div>
      Id of movie: {id}
      {JSON.stringify(data)}
      {isError && <p>{error}</p>}
      {isLoading && <p>Loading...</p>}
    </div>
  )
}
