import Head from 'next/head'
import { DataProvider } from '../components/DataProvider'
import styles from '../styles/Home.module.css'
import config from '../utils/config'
import { useState } from 'react'
import { SearchInput } from '../components/Search'

export default function Home(): JSX.Element {
  const [searchPhrase, setSearchPhrase] = useState<string>(
    ''
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>{config.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchInput
        searchPhrase={searchPhrase}
        setSearchPhrase={setSearchPhrase}
      />
      {!!searchPhrase ? (
        <DataProvider searchPhrase={searchPhrase} />
      ) : (
        'Start typing!'
      )}
    </div>
  )
}
